### ISSUE TITLE
server_test.py failed

### ISSUE THREAD

**Issue by lbazan** [danvk/RangeHTTPServer#21]
================================================================ test session starts =================================================================
platform linux -- Python 3.7.2, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
rootdir: /home/lbazan/rpmbuild/BUILD/RangeHTTPServer-1.2.0, inifile:
plugins: cov-2.5.1
collected 11 items                                                                                                                                   

tests/RangeHTTPServer_test.py ..                                                                                                               [ 18%]
tests/server_test.py

**Comment by danvk** [comment]
Can't reproduce.

```
$ pytest
============================================ test session starts =============================================
platform darwin -- Python 3.11.2, pytest-7.2.2, pluggy-1.0.0
rootdir: /Users/danvk/github/RangeHTTPServer
collected 11 items

tests/RangeHTTPServer_test.py ..                                                                       [ 18%]
tests/server_test.py .........                                                                         [100%]

============================================= 11 passed in 1.59s =============================================
```
