### ISSUE TITLE
pip3 cannot install the newest version

### ISSUE THREAD

**Issue by GarfieldJiang** [danvk/RangeHTTPServer#22]
There is no port arguments in the source file downloaded by pip3

**Comment by ThomasDevoogdt** [comment]
I'm missing https://github.com/danvk/RangeHTTPServer/commit/b440429de07f7ab78ee0e669a1a04efae548d815
in the pip3 version. A new tag should be created!

**Comment by danvk** [comment]
@ThomasDevoogdt are you interested in taking this over? I haven't used RangeHTTPServer since I learned that node's built-in `http-server` supported range requests.

**Comment by ThomasDevoogdt** [comment]
I'm not very known with the python http server and range requests. I just learned last week (related to rauc streaming upgrades) that the default server is not capable of serving range request. I just came across this repo, and fixed the issue myself without knowing about the mentioned commit. To be double checked, but I think that you can simply add a new release tag, and that pip will do the rest.
