### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [danvk/RangeHTTPServer#34]
Could you please tag the source again? This allows distributions to get the complete source from GitHub if they want.

Thanks

**Comment by kloczek** [comment]
+1

**Comment by danvk** [comment]
Done: https://github.com/danvk/RangeHTTPServer/releases/tag/1.3.3

I'd like to transfer ownership of this project to someone who actively uses it. See https://github.com/danvk/RangeHTTPServer/issues/35 if either of you are interested.

**Comment by kloczek** [comment]
Thank you 👍
